name: PR Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    uses: TheManOfTeel/SharedWorkflows/.github/workflows/node-ci.yml@v1.0.0
    with:
      node-version: '24'
      working-directory: .
      install-command: npm install --no-fund --no-audit
      build-command: npm run build --if-present
      test-command: npm test
